# Generated by Django 4.2 on 2023-04-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path_of_file", models.CharField(max_length=300)),
                ("transcription", models.CharField(max_length=500)),
            ],
        ),
    ]
