# Generated by Django 4.2 on 2023-04-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mymodel",
            name="path_of_audio_file",
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
